//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNT_Client.KNT_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/KNT_Service.Wrapper")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _currentMarkerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _diceRollField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _goldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _goldYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _holdingMarkerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _inPhaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, bool> _myMarkersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Tile> _ownedTilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _playerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, KNT_Client.KNT_ServiceReference.Thing> _rackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _thingsInPlayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _turnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _currentMarkerID {
            get {
                return this._currentMarkerIDField;
            }
            set {
                if ((this._currentMarkerIDField.Equals(value) != true)) {
                    this._currentMarkerIDField = value;
                    this.RaisePropertyChanged("_currentMarkerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _diceRoll {
            get {
                return this._diceRollField;
            }
            set {
                if ((this._diceRollField.Equals(value) != true)) {
                    this._diceRollField = value;
                    this.RaisePropertyChanged("_diceRoll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _gold {
            get {
                return this._goldField;
            }
            set {
                if ((this._goldField.Equals(value) != true)) {
                    this._goldField = value;
                    this.RaisePropertyChanged("_gold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _goldY {
            get {
                return this._goldYField;
            }
            set {
                if ((this._goldYField.Equals(value) != true)) {
                    this._goldYField = value;
                    this.RaisePropertyChanged("_goldY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _holdingMarker {
            get {
                return this._holdingMarkerField;
            }
            set {
                if ((this._holdingMarkerField.Equals(value) != true)) {
                    this._holdingMarkerField = value;
                    this.RaisePropertyChanged("_holdingMarker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _inPhase {
            get {
                return this._inPhaseField;
            }
            set {
                if ((this._inPhaseField.Equals(value) != true)) {
                    this._inPhaseField = value;
                    this.RaisePropertyChanged("_inPhase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, bool> _myMarkers {
            get {
                return this._myMarkersField;
            }
            set {
                if ((object.ReferenceEquals(this._myMarkersField, value) != true)) {
                    this._myMarkersField = value;
                    this.RaisePropertyChanged("_myMarkers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Tile> _ownedTiles {
            get {
                return this._ownedTilesField;
            }
            set {
                if ((object.ReferenceEquals(this._ownedTilesField, value) != true)) {
                    this._ownedTilesField = value;
                    this.RaisePropertyChanged("_ownedTiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _playerNumber {
            get {
                return this._playerNumberField;
            }
            set {
                if ((this._playerNumberField.Equals(value) != true)) {
                    this._playerNumberField = value;
                    this.RaisePropertyChanged("_playerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, KNT_Client.KNT_ServiceReference.Thing> _rack {
            get {
                return this._rackField;
            }
            set {
                if ((object.ReferenceEquals(this._rackField, value) != true)) {
                    this._rackField = value;
                    this.RaisePropertyChanged("_rack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _thingsInPlay {
            get {
                return this._thingsInPlayField;
            }
            set {
                if ((object.ReferenceEquals(this._thingsInPlayField, value) != true)) {
                    this._thingsInPlayField = value;
                    this.RaisePropertyChanged("_thingsInPlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _turn {
            get {
                return this._turnField;
            }
            set {
                if ((this._turnField.Equals(value) != true)) {
                    this._turnField = value;
                    this.RaisePropertyChanged("_turn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tile", Namespace="http://schemas.datacontract.org/2004/07/KNT_Service.Wrapper")]
    [System.SerializableAttribute()]
    public partial class Tile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _combatFlaggedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _faceUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _fortLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _hexNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _hexTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _nHexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _neHexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _nwHexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _p1StackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _p2StackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _p3StackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _p4StackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KNT_Client.KNT_ServiceReference.Player _playerAbleToStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KNT_Client.KNT_ServiceReference.Player _playerControlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _playerControlBoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _roughField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _sHexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _seHexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing>> _stacksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _startPossibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _swHexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _traversedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _combatFlagged {
            get {
                return this._combatFlaggedField;
            }
            set {
                if ((this._combatFlaggedField.Equals(value) != true)) {
                    this._combatFlaggedField = value;
                    this.RaisePropertyChanged("_combatFlagged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _faceUp {
            get {
                return this._faceUpField;
            }
            set {
                if ((this._faceUpField.Equals(value) != true)) {
                    this._faceUpField = value;
                    this.RaisePropertyChanged("_faceUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _fortLevel {
            get {
                return this._fortLevelField;
            }
            set {
                if ((this._fortLevelField.Equals(value) != true)) {
                    this._fortLevelField = value;
                    this.RaisePropertyChanged("_fortLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _hexNumber {
            get {
                return this._hexNumberField;
            }
            set {
                if ((this._hexNumberField.Equals(value) != true)) {
                    this._hexNumberField = value;
                    this.RaisePropertyChanged("_hexNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _hexType {
            get {
                return this._hexTypeField;
            }
            set {
                if ((object.ReferenceEquals(this._hexTypeField, value) != true)) {
                    this._hexTypeField = value;
                    this.RaisePropertyChanged("_hexType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _nHex {
            get {
                return this._nHexField;
            }
            set {
                if ((this._nHexField.Equals(value) != true)) {
                    this._nHexField = value;
                    this.RaisePropertyChanged("_nHex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _neHex {
            get {
                return this._neHexField;
            }
            set {
                if ((this._neHexField.Equals(value) != true)) {
                    this._neHexField = value;
                    this.RaisePropertyChanged("_neHex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _nwHex {
            get {
                return this._nwHexField;
            }
            set {
                if ((this._nwHexField.Equals(value) != true)) {
                    this._nwHexField = value;
                    this.RaisePropertyChanged("_nwHex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _p1Stack {
            get {
                return this._p1StackField;
            }
            set {
                if ((object.ReferenceEquals(this._p1StackField, value) != true)) {
                    this._p1StackField = value;
                    this.RaisePropertyChanged("_p1Stack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _p2Stack {
            get {
                return this._p2StackField;
            }
            set {
                if ((object.ReferenceEquals(this._p2StackField, value) != true)) {
                    this._p2StackField = value;
                    this.RaisePropertyChanged("_p2Stack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _p3Stack {
            get {
                return this._p3StackField;
            }
            set {
                if ((object.ReferenceEquals(this._p3StackField, value) != true)) {
                    this._p3StackField = value;
                    this.RaisePropertyChanged("_p3Stack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> _p4Stack {
            get {
                return this._p4StackField;
            }
            set {
                if ((object.ReferenceEquals(this._p4StackField, value) != true)) {
                    this._p4StackField = value;
                    this.RaisePropertyChanged("_p4Stack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KNT_Client.KNT_ServiceReference.Player _playerAbleToStart {
            get {
                return this._playerAbleToStartField;
            }
            set {
                if ((object.ReferenceEquals(this._playerAbleToStartField, value) != true)) {
                    this._playerAbleToStartField = value;
                    this.RaisePropertyChanged("_playerAbleToStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KNT_Client.KNT_ServiceReference.Player _playerControl {
            get {
                return this._playerControlField;
            }
            set {
                if ((object.ReferenceEquals(this._playerControlField, value) != true)) {
                    this._playerControlField = value;
                    this.RaisePropertyChanged("_playerControl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _playerControlBool {
            get {
                return this._playerControlBoolField;
            }
            set {
                if ((this._playerControlBoolField.Equals(value) != true)) {
                    this._playerControlBoolField = value;
                    this.RaisePropertyChanged("_playerControlBool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _rough {
            get {
                return this._roughField;
            }
            set {
                if ((this._roughField.Equals(value) != true)) {
                    this._roughField = value;
                    this.RaisePropertyChanged("_rough");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _sHex {
            get {
                return this._sHexField;
            }
            set {
                if ((this._sHexField.Equals(value) != true)) {
                    this._sHexField = value;
                    this.RaisePropertyChanged("_sHex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _seHex {
            get {
                return this._seHexField;
            }
            set {
                if ((this._seHexField.Equals(value) != true)) {
                    this._seHexField = value;
                    this.RaisePropertyChanged("_seHex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing>> _stacks {
            get {
                return this._stacksField;
            }
            set {
                if ((object.ReferenceEquals(this._stacksField, value) != true)) {
                    this._stacksField = value;
                    this.RaisePropertyChanged("_stacks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _startPossible {
            get {
                return this._startPossibleField;
            }
            set {
                if ((this._startPossibleField.Equals(value) != true)) {
                    this._startPossibleField = value;
                    this.RaisePropertyChanged("_startPossible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _swHex {
            get {
                return this._swHexField;
            }
            set {
                if ((this._swHexField.Equals(value) != true)) {
                    this._swHexField = value;
                    this.RaisePropertyChanged("_swHex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _traversed {
            get {
                return this._traversedField;
            }
            set {
                if ((this._traversedField.Equals(value) != true)) {
                    this._traversedField = value;
                    this.RaisePropertyChanged("_traversed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Thing", Namespace="http://schemas.datacontract.org/2004/07/KNT_Service.Wrapper")]
    [System.SerializableAttribute()]
    public partial class Thing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _combatValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _goldValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _hexTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _inBankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _isOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _onRackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _combatValue {
            get {
                return this._combatValueField;
            }
            set {
                if ((this._combatValueField.Equals(value) != true)) {
                    this._combatValueField = value;
                    this.RaisePropertyChanged("_combatValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _goldValue {
            get {
                return this._goldValueField;
            }
            set {
                if ((this._goldValueField.Equals(value) != true)) {
                    this._goldValueField = value;
                    this.RaisePropertyChanged("_goldValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _hexType {
            get {
                return this._hexTypeField;
            }
            set {
                if ((object.ReferenceEquals(this._hexTypeField, value) != true)) {
                    this._hexTypeField = value;
                    this.RaisePropertyChanged("_hexType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _inBank {
            get {
                return this._inBankField;
            }
            set {
                if ((this._inBankField.Equals(value) != true)) {
                    this._inBankField = value;
                    this.RaisePropertyChanged("_inBank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _isOwned {
            get {
                return this._isOwnedField;
            }
            set {
                if ((this._isOwnedField.Equals(value) != true)) {
                    this._isOwnedField = value;
                    this.RaisePropertyChanged("_isOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _onRack {
            get {
                return this._onRackField;
            }
            set {
                if ((this._onRackField.Equals(value) != true)) {
                    this._onRackField = value;
                    this.RaisePropertyChanged("_onRack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _type {
            get {
                return this._typeField;
            }
            set {
                if ((object.ReferenceEquals(this._typeField, value) != true)) {
                    this._typeField = value;
                    this.RaisePropertyChanged("_type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Board", Namespace="http://schemas.datacontract.org/2004/07/KNT_Service.Wrapper")]
    [System.SerializableAttribute()]
    public partial class Board : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Tile> _tilesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Tile> _tiles {
            get {
                return this._tilesField;
            }
            set {
                if ((object.ReferenceEquals(this._tilesField, value) != true)) {
                    this._tilesField = value;
                    this.RaisePropertyChanged("_tiles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KNT_ServiceReference.IKNTNet")]
    public interface IKNTNet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKNTNet/addPlayer", ReplyAction="http://tempuri.org/IKNTNet/addPlayerResponse")]
        KNT_Client.KNT_ServiceReference.Player addPlayer(KNT_Client.KNT_ServiceReference.Player player, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKNTNet/getPlayers", ReplyAction="http://tempuri.org/IKNTNet/getPlayersResponse")]
        System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Player> getPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKNTNet/getCup", ReplyAction="http://tempuri.org/IKNTNet/getCupResponse")]
        System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> getCup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKNTNet/getBank", ReplyAction="http://tempuri.org/IKNTNet/getBankResponse")]
        System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing>> getBank();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKNTNet/getCurrentPlayer", ReplyAction="http://tempuri.org/IKNTNet/getCurrentPlayerResponse")]
        KNT_Client.KNT_ServiceReference.Player getCurrentPlayer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKNTNet/getMap", ReplyAction="http://tempuri.org/IKNTNet/getMapResponse")]
        KNT_Client.KNT_ServiceReference.Board getMap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKNTNet/connect", ReplyAction="http://tempuri.org/IKNTNet/connectResponse")]
        KNT_Client.KNT_ServiceReference.Player connect(string player);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKNTNetChannel : KNT_Client.KNT_ServiceReference.IKNTNet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KNTNetClient : System.ServiceModel.ClientBase<KNT_Client.KNT_ServiceReference.IKNTNet>, KNT_Client.KNT_ServiceReference.IKNTNet {
        
        public KNTNetClient() {
        }
        
        public KNTNetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KNTNetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KNTNetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KNTNetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KNT_Client.KNT_ServiceReference.Player addPlayer(KNT_Client.KNT_ServiceReference.Player player, string name) {
            return base.Channel.addPlayer(player, name);
        }
        
        public System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Player> getPlayers() {
            return base.Channel.getPlayers();
        }
        
        public System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing> getCup() {
            return base.Channel.getCup();
        }
        
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<KNT_Client.KNT_ServiceReference.Thing>> getBank() {
            return base.Channel.getBank();
        }
        
        public KNT_Client.KNT_ServiceReference.Player getCurrentPlayer() {
            return base.Channel.getCurrentPlayer();
        }
        
        public KNT_Client.KNT_ServiceReference.Board getMap() {
            return base.Channel.getMap();
        }
        
        public KNT_Client.KNT_ServiceReference.Player connect(string player) {
            return base.Channel.connect(player);
        }
    }
}
